TRUTH = (
    "Have you ghosted someone?"
    "Have you ever walked in on your parents doing 'it'?",
    "Who was the last person you liked the most? Why?",
    "Have you ever been suspended from school?",
    "If you had to choose between going naked or having your thoughts appear in thought bubbles above your head for everyone to read, which would you choose?",
    "What’s the one thing you’re afraid to lose?",
    "Do you like someone as of the moment?",
    "One thing about your best friend you are jealous of?",
    "Would you cheat on your boyfriend for a rich guy?",
    "What is your biggest turn on?",
    "When’s the last time you lied to your parents and why?",
    "Describe your ideal partner.",
    "What’s the scariest thing you’ve ever done?",
    "Have you ever picked your nose and eaten it?",
    "When’s the last time you lied to your parents and why?",
    "Have you ever lied about your age to participate in a contest?",
    "Have you ever been caught checking someone out?",
    "Have your ever sleep-walked?",
    "What's your favorite holiday and why?",
    "If you life was made into a movie, which actor/actress would play you?",
    "If you had only 1 more day to live, what would you do?",
    "Would you rather be able to change the past or see into the future?",
    "What's the weirdest thing about you? Are you proud of it?",
    "What's the best part about having/not having siblings?",
    "What was the best day of your life?",
    "What's your favorite movie quote?",
    "Who in your opinion is the lamest celebrity?",
    "What's your favorite junk food?",
    "Would you prefer to be smart or happy, and why?",
    "Do you keep a diary or a journal?",
    "If you win a 1.000.000$, what would you do with the money?",
    "Who's your celebrity crush?",
    "What's your dream vacation?",
    "Have you ever thought about changing your name? If yes, to what?",
    "Are you a morning person or a night owl?",
    "Are there any rules or social norms that piss you off?",
    "What food would you never give up in a million years?",
    "What's the maximum amount you think you can survive without your cell phone?",
    "Which fictional charcater would you love to marry?",
    "If you could have 1 superpower, which would you choose?",
    "What was your best Halloween costume ever?",
    "What's the worst job you could possibly have?",
    "Have you ever lied in Truth or Dare questions?",
    "What do you follow most often - your head or your heart?",
    "What are the things on your 'bucket' list?",
    "What's your biggest shopping addiction?",
    "If you were a king of your own kingdom, what would be your first order?",
    "If you had only 1 more day to live, what would you do?",
    "Have you ever kept a New Year's resolution? If yes, which one(s)?",
    "Do you think Earth is the only inhabitable planet? Do you believe in aliens?",
    "What was the best compliment you've ever received and given?",
    "Have you ever thought about changing your name? If yes, to what?",
    "Have you ever sneaked snacks when your parents weren't looking?",
    "If you write a book, what would it be about?",
    "If you could make one of your dreams come true, which would it be?",
    "Do you have any scars? If so, how did you get the first one?",
    "What's the most beautiful place you've ever been to?",
    "What's the TV show you binge-watched all day?",
    "Where do you want to be right now?",
    "What do you follow most often - your head or your heart?",
    "If you could shop for free in one store, which one would you pick?",
    "What particular detail turns you on about people you find attractive?",
    "Have you ever had any regrets having slept with somebody? If so, why?",
    "What's the strangest place in which you've had sex?",
    "Would you prefer to date someone younger or older than you?",
    "Could you make out with someone to climb up the social ladder?",
    "What is the perfect underwear for you?",
    "What's the stupidest thing you've ever done for love?",
    "Have you ever gone on a blind date?",
    "What is your least favorite position?",
    "When did you masturbate for the last time?",
    "Have you ever gotten crazy drunk alone on Valentine's Day?",
    "Where do you like to be touched?",
    "Do you prefer to have music in the background, or for it to be quiet?",
    "How many partners max have you had at one time?",
    "Have you ever gotten crazy drunk alone on Valentine's Day?",
    "What do you appreciate more - love or money?",
    "Have you ever made a sexy video of yourself?",
    "Describe your perfect date for Valentine's.",
    "Rank your sexual partners",
    "Who was your first crush?",
    "Who is your favorite porn star?",
    "Who was your first partner?",
    "When was your biggest drinking night? (you got plastered and threw up)",
    "What's the craziest thing you've ever done in bed?",
    "What is your favorite type of foreplay?",
    "What is your biggest fear in a relationship?",
    "What would be a perfect sex toy for you?",
    "What is your role-playing fantasy?",
    "Have you ever had sex outside?",
    "Where is your favorite place to be kissed?",
    "Would you ever watch your partner have sex with someone else?",
    "Do you like anal?",
    "Have you ever had sex with someone of the same gender?",
    "Have you ever been in a serious relationship?",
    "Do you expect to finish this Valentine's Day with sex?",
    "Do you enjoy rough or slow sex?",
    "Have you ever watched an 'adult' movie?",
    "have u ever hear sound of your parent doing intercourse?",
    "Who in this room you'd like to kiss?",
   )

DARE = (  
    "Show the most embarrassing photo on your phone"
    "Show the last five people you texted and what the messages said",
    "Let the rest of the group DM someone from your Instagram account",
    "Eat a raw piece of garlic",
    "Do 100 squats",
    "Keep three ice cubes in your mouth until they melt",
    "Say something dirty to the person on your leftYou've got company!",
    "Give a foot massage to the person on your right",
    "Put 10 different available liquids into a cup and drink it"
    "*Yell out the first word that comes to your mind",
    "Give a lap dance to someone of your choice",
    "Remove four items of clothing",
    "Like the first 15 posts on your Facebook newsfeed",
    "Eat a spoonful of mustard",
    "Keep your eyes closed until it's your go again",
    "Send a sext to the last person in your phonebook",
    "Show off your orgasm face",
    "Seductively eat a banana",
    "Empty out your wallet/purse and show everyone what's inside",
    "Do your best sexy crawl",
    "Pretend to be the person to your right for 10 minutes",
    "Eat a snack without using your hands",
    "Say two honest things about everyone else in the group",
    "Twerk for a minute",
    "Try and make the group laugh as quickly as possible",
    "Try to put your whole fist in your mouth",
    "Tell everyone an embarrassing story about yourself",
    "Try to lick your elbow",
    "Post the oldest selfie on your phone on Instagram Stories",
    "Tell the saddest story you know",
    "Howl like a wolf for two minutes",
    "Dance without music for two minutes",
    "Pole dance with an imaginary pole",
    "Let someone else tickle you and try not to laugh",
    "Put as many snacks into your mouth at once as you can",
    "Send your most recent selfie.",
    "Send your ugliest selfie.",
    "Send a screenshot of your facebook search history",
    "Send a screenshot of your gallery.",
    "Send a screenshot of your messenger inbox",
    "Tell something very intimate.",
    "Send a screenshot of your twitter inbox",
    "Send a screenshot of your homescreen.",
    "Send a cover of your favorite song. 🎤",
    "Do a lyric prank on someone and send proof.",
    "Confess to your current crush. ❤️",
    "Declare who is your true love.",
    "Send a screenshot of your gallery.",
    "Set your crush’s picture as your dp.",
    "Suggest me more dares.",
)

SIMP = (
    "Can I Tie Your Shoes? Cause I Don’t Want You To Fall For Someone Else.",
    " It’s A Good Thing I Have My Library Card, Because I’m Totally Checking You Out.",
    " I Was Wondering If You’re An Artist Because You Were So Good At Drawing Me In.",
    "You May Fall From The Sky, You May Fall From A Tree, But The Best Way To Fall... Is In Love With Me.",
    "Roses Are Red, I Have A Crush, Whenever I’m Around You, All I Do Is Blush.",
    "Forget About Spiderman, Superman, And Batman. I'll Be Your Man.",
    "There Isn't A Word In The Dictionary For How Good You Look.",
    "My Buddies Bet Me That I Wouldn’t Be Able To Start A Conversation With The Most Beautiful Girl In The Bar. Wanna Buy Some Drinks With Their Money?",
    " Excuse Me, May I Sit Here For A Moment To Recuperate From Falling For You?",
    "It's A Good Thing I Wore Gloves Today. Otherwise, You'd Be Too Hot To Handle.",
    "Do You Know What My Shirt Is Made Of? Boyfriend/Girlfriend Material?",
    "I’m Not A Photographer, But I Can Picture Me And You Together.",
    "I’m Going To The Optometrist To Get My Eyes Checked. For Some Reason, I Can’t Take Them Off Of You.",
    "Wouldn’t We Look Good On A Wedding Cake Together?",
    "I Think There’s Something Wrong With My Phone. Could You Try Calling It To See If It Works?",
    "We’re Not Socks, But I Think We’d Make A Great Pair.",
    "all Me Q Because I Need U Next To Me At All Times.",
    "Even If There Was No Gravity On Planet Earth, I Would Still Fall For You.",
    "They Say Disneyland Is The Happiest Place On Earth. Well Apparently, No One Has Ever Been Standing Next To You."
    "Even If There Was No Gravity On Planet Earth, I Would Still Fall For You.",
    "The Sparkle In Your Eyes Is So Bright, The Sun Must Be Jealous",
    "On A Scale Of 1 To 10, You're A 9. I'm The 1 You Need.",
    "Are You The Moon? Because Even When It's Dark, You Still Seem To Shine.",
    "Well, Here I Am. What Are Your Other Two Wishes?",
    "Are You A Dictionary? ‘Cause You’re Adding Meaning To My Life.",
    "Hi, I’m Mr. Right. Someone Said You Were Looking For Me?",
    "Excuse Me. I Know This Is Kind Of Weird And I’m Super Shy…But I Was Just Wondering…What Pick Up Lines Work Best With You?",
    "Are You A Magician? Because Whenever I Look At You, Everyone Else Disappears!",
    "I Might Need A Pair Of Sunglasses Because Your Smile Is Too Dazzling For Me.",
    "If You Could Read My Thoughts, You Would Marry Me Tomorrow.",
    "Have You Been To The Doctor’s Lately? Because I Think You’re Lacking Some Vitamin Me.",
    "Is Your Name Ariel? Cause We Mermaid For Each Other!",
    " Hey, My Name's Microsft. Can I Crash At Your Place Tonight?",
    "You Know, I Had A Pickup Line Ready To Go, But You’re So Hot It Just Left My Mind.",
    "Are You A Keyboard? Because You’re My Type!",
    "Is There An Airport Nearby Or Is It My Heart Taking Off?",
    "If Being Sexy Was A Crime, You’d Be In Prison For Life!",
)
